const { sources, places, events, notices, news, services } = window.CAMPUS_DATA;

const app = document.querySelector('#app');
const campusAddress = 'Ramaiah Institute of Technology, MSR Nagar, Bengaluru 560054';
const googleMapUrl = (query) => `https://www.google.com/maps?q=${encodeURIComponent(query)}&z=16&output=embed`;
const directionsUrl = (destination, origin='') => `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}${origin ? `&origin=${encodeURIComponent(origin)}` : ''}`;
let googleMapsPromise;
function loadGoogleMaps(){ const key=window.CAMPUS_RUNTIME?.googleMapsApiKey; if(!key) return Promise.resolve(false); if(window.google?.maps) return Promise.resolve(true); if(!googleMapsPromise) googleMapsPromise=new Promise(resolve=>{ const script=document.createElement('script'); script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&libraries=places`; script.async=true; script.onload=()=>resolve(true); script.onerror=()=>resolve(false); document.head.append(script); }); return googleMapsPromise; }
async function initialiseGoogleMap(){ const host=document.querySelector('[data-google-map]'); if(!host) return; if(!await loadGoogleMaps()){ host.innerHTML='<div class="map-api-empty"><b>Google Maps needs a browser key.</b><span>Add GOOGLE_MAPS_API_KEY, restart the local server, then reload this page.</span><a href="https://www.google.com/maps/search/?api=1&query=Ramaiah%20Institute%20of%20Technology" target="_blank" rel="noreferrer">Open MSRIT in Google Maps ↗</a></div>'; return; } const center={lat:13.03092,lng:77.56523}; const map=new google.maps.Map(host,{center,zoom:16,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,styles:[{elementType:'geometry',stylers:[{color:'#11111a'}]},{elementType:'labels.text.fill',stylers:[{color:'#d8ffd7'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#27263a'}]},{featureType:'water',elementType:'geometry',stylers:[{color:'#061f2d'}]}]}); new google.maps.Marker({position:center,map,title:'Ramaiah Institute of Technology'}); window.CAMPUS_GOOGLE_MAP=map; }
const icon = (name) => ({search:'⌕', map:'⌖', calendar:'◷', spark:'✦', arrow:'→', pin:'●', menu:'☰', close:'×', external:'↗', shield:'◆', filter:'≡', home:'⌂', bell:'◉', people:'◎'})[name] || '•';
const source = (key) => { const s=sources[key]; return `<a class="badge ${s.level === 'Demo data' ? 'demo' : ''}" href="${s.url}" target="_blank" rel="noreferrer">${s.level === 'Official' ? icon('shield')+' ' : ''}${s.name}</a>` };
const esc = (v='') => String(v).replace(/[&<>'"]/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));
const nav = () => `<header><a class="brand" href="/" data-link><span class="brand-mark">C</span><span>Campus <b>OS</b></span></a><nav><a href="/explore" data-link>Explore</a><a href="/map" data-link>Map</a><a href="/events" data-link>Events</a><a href="/notices" data-link>Notices</a><a href="/directory" data-link>Directory</a></nav><div class="header-actions"><button class="icon-button" data-search aria-label="Open search">${icon('search')}</button><a class="ask-btn" href="/ask" data-link>${icon('spark')} Ask Campus OS</a></div></header>`;
const mobile = () => `<nav class="mobile-nav"><a href="/" data-link>${icon('home')}<span>Home</span></a><a href="/explore" data-link>${icon('search')}<span>Explore</span></a><a href="/map" data-link>${icon('map')}<span>Map</span></a><a href="/events" data-link>${icon('calendar')}<span>Events</span></a><a href="/ask" data-link class="ask-mobile">${icon('spark')}<span>Ask</span></a></nav>`;
const shell = (content) => `${nav()}<main>${content}</main>${mobile()}<div class="search-overlay" hidden></div>`;
const action = (href, ic, title, body) => `<a href="${href}" data-link class="quick-action"><span>${icon(ic)}</span><b>${title}</b><small>${body}</small>${icon('arrow')}</a>`;
const itemCard=(item,type)=> `<article class="item-card"><div class="item-top"><span class="eyebrow">${item.category || type}</span>${source(item.source)}</div><h3>${esc(item.title||item.name)}</h3><p>${esc(item.summary||item.description)}</p><div class="card-meta">${item.date ? `<span>${esc(item.date)}</span>`:''}${item.location ? `<span>${icon('pin')} ${esc(item.location)}</span>`:''}</div><a href="/${type}/${item.slug || item.id}" data-link class="text-link">Open ${type} ${icon('arrow')}</a></article>`;
function home(){ return shell(`<section class="hero"><div class="hero-copy"><p class="kicker">M. S. Ramaiah Institute of Technology</p><h1>Your campus,<br/><em>connected.</em></h1><p class="lede">Find places, understand what is happening, and get answers grounded in clear sources.</p><form class="hero-search" data-search-form><span>${icon('search')}</span><input autofocus name="q" placeholder="Search rooms, events, departments, notices..." aria-label="Search Campus OS"/><button>Search</button></form><div class="trust-row"><span>${icon('shield')} Sources shown</span><span>${icon('map')} Map-aware</span><span>${icon('spark')} Answers grounded</span></div></div><div class="hero-map"><div class="map-grid"></div><span class="map-label l1">Academic Block</span><span class="map-label l2">Student Centre</span><span class="map-label l3">Admin</span><i class="marker m1"></i><i class="marker m2"></i><i class="marker m3"></i><div class="map-callout"><span>${icon('pin')}</span><div><b>Find your way</b><small>Explore the campus map</small></div><a href="/map" data-link>${icon('arrow')}</a></div></div></section><section class="quick"><div class="section-title"><div><p class="kicker">Start here</p><h2>Make campus simpler</h2></div></div><div class="quick-grid">${action('/map','map','Find a place','Buildings, services & landmarks')}${action('/events','calendar','What’s happening?','Today, this week and beyond')}${action('/notices','bell','Notices','Official updates and documents')}${action('/ask','spark','Ask Campus OS','Answers with sources')}</div></section><section class="split-section"><div><div class="section-title"><div><p class="kicker">Today</p><h2>On campus</h2></div><a href="/events" data-link>All events ${icon('arrow')}</a></div><div class="stack">${events.slice(0,2).map(e=>itemCard(e,'events')).join('')}</div></div><aside class="notice-panel"><div class="section-title"><div><p class="kicker">Latest</p><h2>Notices</h2></div><a href="/notices" data-link>View all ${icon('arrow')}</a></div>${notices.map(n=>`<a class="notice-row ${n.urgent?'urgent':''}" href="/notices/${n.slug}" data-link><span>${n.urgent?'Important':'Official'}</span><b>${n.title}</b><small>${n.date}</small></a>`).join('')}</aside></section><section class="explore-band"><div><p class="kicker">Explore campus</p><h2>A map with context.</h2><p>Locations carry category, accessibility and source information, so the map stays useful even when exact indoor directions are unavailable.</p><a href="/map" data-link class="outline-btn">Open map ${icon('arrow')}</a></div><div class="place-list">${places.slice(0,4).map(p=>`<a href="/map?place=${p.id}" data-link><span>${icon('pin')}</span><div><b>${p.name}</b><small>${p.category} · ${p.building}</small></div>${icon('arrow')}</a>`).join('')}</div></section>`); }
function listPage(kind, title, subtitle, data, filters=[]){ const cards=data.map(x=>itemCard(x,kind)).join(''); return shell(`<section class="page-head"><p class="kicker">Campus OS</p><h1>${title}</h1><p>${subtitle}</p>${filters.length?`<div class="filters"><button class="active">All</button>${filters.map(x=>`<button>${x}</button>`).join('')}</div>`:''}</section><section class="content-grid">${cards || `<div class="empty">Nothing is available yet.</div>`}</section>`); }
function mapPage(){ return shell(`<section class="map-page"><aside class="map-sidebar"><p class="kicker">Campus map</p><h1>Find your way.</h1><p>Google Maps shows the real campus area. Campus OS points remain approximate until MSRIT verifies building-level coordinates.</p><label class="map-search">${icon('search')}<input placeholder="Search Campus OS places" data-map-search/></label><div class="map-filters"><button class="active">All</button><button>Academic</button><button>Food</button><button>Services</button></div><div class="place-results">${places.map(p=>`<button data-place="${p.id}"><span>${icon('pin')}</span><div><b>${p.name}</b><small>${p.category} · ${p.building}</small></div>${source(p.source)}</button>`).join('')}</div></aside><div class="campus-map google-map-panel"><div role="application" aria-label="Google map of the MSRIT campus" data-google-map></div><div class="map-tools"><form data-google-search><input name="place" placeholder="Search an address or landmark" aria-label="Search Google Maps"/><button>Search map</button></form><button class="location-button" data-current-location>${icon('pin')} Use my location</button><a href="${directionsUrl(campusAddress)}" target="_blank" rel="noreferrer">Open Google Maps ${icon('external')}</a></div><div class="map-legend"><b>${icon('map')} Live Google Maps</b><small>Exact location requires device permission.</small></div><div class="place-detail" hidden></div></div></section>`); }
function directory(){ return shell(`<section class="page-head"><p class="kicker">Directory & services</p><h1>Useful campus links.</h1><p>Authenticated systems remain official. Campus OS only links to public or officially supported services.</p></section><section class="service-grid">${services.map(s=>`<article class="service-card"><div>${icon('external')}</div><h3>${s.name}</h3><p>${s.description}</p>${source(s.source)}<a href="${s.url}" target="_blank" rel="noreferrer">Visit source ${icon('arrow')}</a></article>`).join('')}</section>`); }
function ask(){ return shell(`<section class="ask-page"><div class="ask-intro"><p class="kicker">Ask Campus OS</p><h1>Answers with<br/><em>receipts.</em></h1><p>Searches structured campus content first. When evidence is missing, it says so.</p><div class="suggestions"><button>Where is the CSE department?</button><button>What events are happening tomorrow?</button><button>Where can I get exam documents?</button></div></div><section class="chat"><div class="chat-status">${icon('shield')} Source-aware answers · Demo knowledge base</div><div class="messages" aria-live="polite"><div class="assistant-msg"><b>Campus OS</b><p>What can I help you find?</p></div></div><form class="ask-input"><input placeholder="Ask about places, events or services..." aria-label="Ask Campus OS"/><button aria-label="Send">${icon('arrow')}</button></form></section></section>`); }
function admin(){ return shell(`<section class="admin"><div class="admin-head"><div><p class="kicker">Administration</p><h1>Review queue</h1><p>Content moves through fetched, normalized, review and published stages.</p></div><button class="primary">Add content</button></div><div class="admin-stats"><div><span>Sources</span><b>3</b><small>2 active</small></div><div><span>Pending review</span><b>2</b><small>Demo records</small></div><div><span>Published</span><b>4</b><small>Source shown</small></div></div><div class="admin-table"><div class="table-head"><b>Content</b><b>Source</b><b>Status</b><b>Updated</b></div>${[...events,...notices].map(x=>`<div><span><b>${x.title}</b><small>${x.category}</small></span><span>${source(x.source)}</span><span class="status ${x.status==='Needs verification'?'review':''}">${x.status || 'Published'}</span><span>${x.date}</span></div>`).join('')}</div></section>`); }
function search(q){ const needle=q.toLowerCase().trim(); const all=[...places.map(x=>({...x,type:'places'})),...events.map(x=>({...x,type:'events'})),...notices.map(x=>({...x,type:'notices'})),...news.map(x=>({...x,type:'news'})),...services.map(x=>({...x,type:'services'}))]; return !needle?[]:all.filter(x=>Object.values(x).join(' ').toLowerCase().includes(needle)); }
function searchPage(q=''){ const results=search(q); return shell(`<section class="page-head search-head"><p class="kicker">Search</p><h1>Find what you need.</h1><form class="wide-search" data-search-form><span>${icon('search')}</span><input name="q" value="${esc(q)}" placeholder="Search Campus OS"/><button>Search</button></form>${q?`<p>${results.length} result${results.length===1?'':'s'} for “${esc(q)}”</p>`:'<p>Search places, events, notices, people, departments and services.</p>'}<div class="filters"><button class="active">All</button><button>Places</button><button>Events</button><button>Notices</button><button>Services</button></div></section><section class="content-grid">${results.map(x=>itemCard(x,x.type)).join('') || (q?`<div class="empty"><h2>No exact match</h2><p>Try a broader term or ask Campus OS.</p><a class="primary" href="/ask" data-link>Ask Campus OS</a></div>`:'')}</section>`); }
function route(forcedPath){ const path=forcedPath || (location.protocol==='file:' ? '/' : location.pathname); let page= path==='/'?home():path==='/map'?mapPage():path==='/events'?listPage('events','Events','What’s happening across campus. Verify event details at the original source.',events,['Today','This week','Workshop','Technical','Sports']):path==='/notices'?listPage('notices','Notices','Official updates are clearly separate from community information.',notices,['Official','Academic','Examination','Placement','Student']):path==='/news'?listPage('news','News','Campus news with a visible provenance trail.',news,['Official','Community','External']):path==='/directory'?directory():path==='/ask'?ask():path==='/admin'?admin():path==='/search'?searchPage(new URLSearchParams(location.search).get('q')||''):searchPage(path.split('/').pop().replace(/-/g,' ')); app.innerHTML=page; bind(); initialiseGoogleMap(); bindGoogleMapControls(); bindGeminiAsk(); }
function bind(){
  document.querySelectorAll('[data-link]').forEach(a=>a.addEventListener('click',e=>{
    if(a.target==='_blank')return; e.preventDefault(); const destination=new URL(a.href).pathname;
    if(location.protocol==='file:') route(destination); else { history.pushState({},'',a.href); route(); }
    window.scrollTo({top:0,behavior:'smooth'});
  }));
  document.querySelectorAll('[data-search-form]').forEach(f=>f.addEventListener('submit',e=>{
    e.preventDefault(); const q=new FormData(f).get('q');
    if(location.protocol==='file:'){ app.innerHTML=searchPage(q); bind(); } else { history.pushState({},'',`/search?q=${encodeURIComponent(q)}`); route(); }
  }));
  document.querySelector('[data-search]')?.addEventListener('click',()=> location.protocol==='file:' ? route('/search') : (history.pushState({},'','/search'),route()));
  document.querySelectorAll('[data-place]').forEach(b=>b.addEventListener('click',()=>showPlace(b.dataset.place)));
  document.querySelector('[data-map-search]')?.addEventListener('input',e=>{const n=e.target.value.toLowerCase();document.querySelectorAll('.place-results button').forEach(b=>b.hidden=!b.innerText.toLowerCase().includes(n));});
  document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>askReply(b.textContent)));
  document.querySelector('.ask-input')?.addEventListener('submit',e=>{e.preventDefault();const input=e.currentTarget.querySelector('input');askReply(input.value);input.value='';});
}
function showPlace(id){ const p=places.find(x=>x.id===id); const d=document.querySelector('.place-detail'); if(!p||!d)return; const map=window.CAMPUS_GOOGLE_MAP; if(map && window.google?.maps){ map.panTo({lat:13.03092,lng:77.56523}); map.setZoom(17); } d.hidden=false;d.innerHTML=`<button aria-label="Close">${icon('close')}</button><p class="eyebrow">${p.category}</p><h3>${p.name}</h3><p>${p.description}</p>${source(p.source)}<a class="primary" target="_blank" rel="noreferrer" href="${directionsUrl(`${p.name}, ${campusAddress}`)}">Get directions ${icon('arrow')}</a>`;d.querySelector('button').onclick=()=>d.hidden=true; }
function localAnswer(q){ const results=search(q); if(!results.length) return { answer: "I couldn't verify that from the Campus OS sources yet. Once campus data is added, Gemini will use it as grounded context.", refs: '' }; const top=results.slice(0,3); return { answer:`I found ${top.map(x=>x.title||x.name).join(', ')} in the Campus OS source index.`, refs:top.map(x=>`${source(x.source)} <a href="/${x.type}/${x.slug||x.id}" data-link>Open ${x.type}</a>`).join('') }; }
async function askReply(q){ if(!q?.trim())return; const msgs=document.querySelector('.messages'); if(!msgs)return; msgs.insertAdjacentHTML('beforeend',`<div class="user-msg"><p>${esc(q)}</p></div><div class="assistant-msg thinking"><b>Campus OS</b><p>Thinking with Gemini...</p></div>`); msgs.scrollTop=msgs.scrollHeight; let result=localAnswer(q); if(location.protocol !== 'file:'){ try { const response=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})}); const body=await response.json(); if(response.ok) result={answer:body.answer,refs:'<span class="gemini-source">Gemini response - verify against official sources</span>'}; else if(body.error?.includes('not configured')) result={answer:result.answer,refs:'<span class="gemini-source">Gemini needs GEMINI_API_KEY to be added on the server.</span>'}; } catch { result={answer:'Campus OS could not reach Gemini. Your local source search is still available.',refs:''}; } } const pending=msgs.querySelector('.thinking'); pending?.remove(); msgs.insertAdjacentHTML('beforeend',`<div class="assistant-msg"><b>Campus OS</b><p>${esc(result.answer)}</p><div class="citations">${result.refs}</div></div>`); bind(); msgs.scrollTop=msgs.scrollHeight; }
function bindGoogleMapControls(){ document.querySelector('[data-google-search]')?.addEventListener('submit',e=>{e.preventDefault(); const query=new FormData(e.currentTarget).get('place')?.trim(); if(!query)return; const map=window.CAMPUS_GOOGLE_MAP; if(map && window.google?.maps){ const geocoder=new google.maps.Geocoder(); geocoder.geocode({address:query},(results,status)=>{if(status==='OK'&&results[0]){map.fitBounds(results[0].geometry.viewport);new google.maps.Marker({map,position:results[0].geometry.location,title:results[0].formatted_address});}}); } }); document.querySelector('[data-current-location]')?.addEventListener('click',()=>{const button=document.querySelector('[data-current-location]'); if(!navigator.geolocation){button.textContent='Location unavailable';return;} button.textContent='Locating...'; navigator.geolocation.getCurrentPosition(pos=>{const point={lat:pos.coords.latitude,lng:pos.coords.longitude}; const map=window.CAMPUS_GOOGLE_MAP; if(map && window.google?.maps){map.panTo(point);map.setZoom(17);new google.maps.Marker({map,position:point,title:'Your location'});} button.textContent='Viewing your location';},()=>{button.textContent='Location permission was not granted';},{enableHighAccuracy:true,timeout:10000,maximumAge:60000});}); }
function bindGeminiAsk(){ /* The event handler is installed by bind(); this hook keeps the chat integration explicit. */ }
window.addEventListener('popstate',route);route();
