-- Campus OS foundation schema for Supabase/PostgreSQL. All imported content carries provenance.
create extension if not exists vector;
create type public.content_status as enum ('fetched','normalized','pending_review','published','rejected','archived');
create type public.authority_level as enum ('official_msrIT','affiliated','verified_department','external','community','user_submitted');
create table public.sources (id uuid primary key default gen_random_uuid(), name text not null, type text not null, url text not null, authority_level authority_level not null, sync_method text not null default 'manual', active boolean not null default true, last_checked_at timestamptz, created_at timestamptz not null default now());
create table public.buildings (id uuid primary key default gen_random_uuid(), name text not null, description text, latitude numeric, longitude numeric, address text, image text, accessibility_info text, source_id uuid references public.sources(id));
create table public.departments (id uuid primary key default gen_random_uuid(), name text not null, abbreviation text unique, description text, building_id uuid references public.buildings(id), website text, contact_email text, source_id uuid references public.sources(id));
create table public.floors (id uuid primary key default gen_random_uuid(), building_id uuid not null references public.buildings(id), floor_number integer not null, map_image text);
create table public.rooms (id uuid primary key default gen_random_uuid(), building_id uuid not null references public.buildings(id), floor_id uuid references public.floors(id), room_number text not null, name text, room_type text, description text);
create table public.pois (id uuid primary key default gen_random_uuid(), name text not null, category text not null, building_id uuid references public.buildings(id), floor_id uuid references public.floors(id), room_id uuid references public.rooms(id), latitude numeric, longitude numeric, description text, accessibility_info text, source_id uuid references public.sources(id));
create table public.events (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, description text, category text, start_time timestamptz, end_time timestamptz, location_id uuid references public.pois(id), organizer text, registration_url text, image text, source_id uuid not null references public.sources(id), status content_status not null default 'pending_review', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.notices (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, summary text, content text, category text, published_at timestamptz, expires_at timestamptz, source_id uuid not null references public.sources(id), attachment_url text, status content_status not null default 'pending_review');
create table public.news (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, summary text, content text, image text, published_at timestamptz, source_id uuid not null references public.sources(id), original_url text, status content_status not null default 'pending_review');
create table public.documents (id uuid primary key default gen_random_uuid(), title text not null, source_id uuid not null references public.sources(id), url text, content text, published_at timestamptz, indexed_at timestamptz);
create table public.embeddings (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id), chunk_id text not null, embedding vector(1536), metadata jsonb not null default '{}');
alter table public.sources enable row level security; alter table public.events enable row level security; alter table public.notices enable row level security; alter table public.news enable row level security;
create policy "public reads published events" on public.events for select using (status = 'published');
create policy "public reads published notices" on public.notices for select using (status = 'published');
create policy "public reads published news" on public.news for select using (status = 'published');
-- Add role-aware admin policies after connecting auth.users/profile claims.
